# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_rev01.ui',
# licensing of 'mainWindow_rev01.ui' applies.
#
# Created: Wed Jan  9 16:10:10 2019
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(20, 30, 251, 31))
        self.username.setObjectName("username")
        self.firstName = QtWidgets.QLineEdit(self.centralwidget)
        self.firstName.setGeometry(QtCore.QRect(20, 80, 251, 31))
        self.firstName.setObjectName("firstName")
        self.phoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneNumber.setGeometry(QtCore.QRect(300, 30, 251, 31))
        self.phoneNumber.setObjectName("phoneNumber")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(300, 80, 251, 31))
        self.address.setObjectName("address")
        self.mainTable = QtWidgets.QTableWidget(self.centralwidget)
        self.mainTable.setGeometry(QtCore.QRect(20, 140, 761, 371))
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(5)
        self.mainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(4, item)
        self.mainTable.horizontalHeader().setVisible(True)
        self.mainTable.horizontalHeader().setStretchLastSection(True)
        self.removeRow = QtWidgets.QPushButton(self.centralwidget)
        self.removeRow.setGeometry(QtCore.QRect(680, 40, 99, 27))
        self.removeRow.setObjectName("removeRow")
        self.addData = QtWidgets.QPushButton(self.centralwidget)
        self.addData.setGeometry(QtCore.QRect(680, 90, 99, 27))
        self.addData.setObjectName("addData")
        self.approved = QtWidgets.QCheckBox(self.centralwidget)
        self.approved.setGeometry(QtCore.QRect(550, 0, 131, 51))
        self.approved.setObjectName("approved")
        mainWindow.setCentralWidget(self.centralwidget)
        self.mainMenubar = QtWidgets.QMenuBar(mainWindow)
        self.mainMenubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.mainMenubar.setObjectName("mainMenubar")
        self.menuFile = QtWidgets.QMenu(self.mainMenubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.mainMenubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.mainMenubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.mainMenubar)
        self.mainStatusbar = QtWidgets.QStatusBar(mainWindow)
        self.mainStatusbar.setObjectName("mainStatusbar")
        mainWindow.setStatusBar(self.mainStatusbar)
        self.mainToolbar = QtWidgets.QToolBar(mainWindow)
        self.mainToolbar.setObjectName("mainToolbar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)
        mainWindow.insertToolBarBreak(self.mainToolbar)
        self.actionExport = QtWidgets.QAction(mainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtWidgets.QAction(mainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.mainMenubar.addAction(self.menuFile.menuAction())
        self.mainMenubar.addAction(self.menuEdit.menuAction())
        self.mainMenubar.addAction(self.menuHelp.menuAction())
        self.mainToolbar.addAction(self.actionImport)
        self.mainToolbar.addAction(self.actionExport)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionPreferences)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionAbout)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "PyDataMan 0.1", None, -1))
        self.username.setPlaceholderText(QtWidgets.QApplication.translate("mainWindow", "Username", None, -1))
        self.firstName.setPlaceholderText(QtWidgets.QApplication.translate("mainWindow", "First Name", None, -1))
        self.phoneNumber.setPlaceholderText(QtWidgets.QApplication.translate("mainWindow", "Phone Number", None, -1))
        self.address.setPlaceholderText(QtWidgets.QApplication.translate("mainWindow", "Address", None, -1))
        self.mainTable.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("mainWindow", "Username", None, -1))
        self.mainTable.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("mainWindow", "First Name", None, -1))
        self.mainTable.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("mainWindow", "Phone Number", None, -1))
        self.mainTable.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("mainWindow", "Address", None, -1))
        self.mainTable.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("mainWindow", "Status", None, -1))
        self.removeRow.setText(QtWidgets.QApplication.translate("mainWindow", "Remove Row", None, -1))
        self.addData.setText(QtWidgets.QApplication.translate("mainWindow", "Add Data", None, -1))
        self.approved.setText(QtWidgets.QApplication.translate("mainWindow", "User approved", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("mainWindow", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("mainWindow", "Edit", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("mainWindow", "Help", None, -1))
        self.mainToolbar.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "toolBar", None, -1))
        self.actionExport.setText(QtWidgets.QApplication.translate("mainWindow", "Export", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("mainWindow", "Import", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("mainWindow", "Exit", None, -1))
        self.actionPreferences.setText(QtWidgets.QApplication.translate("mainWindow", "Preferences", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("mainWindow", "About", None, -1))

